### ISSUE TITLE
Confusion with links

### ISSUE THREAD

**Issue by toraritte** [signalwire/freeswitch-docs#35]
First of all, congrats on the migration to Docusaurus! Contributed a lot to the old, Confluence-based docs, but this one looks (and behaves) way better.

As for this issue, a couple of observations about the links in the header and footer:

+ Header > "GitHub" (and under Footer > **More**) link to the `signalwire/freeswitch` repo. This documentation repo is not hard to find, but a link to it would probably be helpful.

+ Footer > **Docs** > "Tutorial" yields a 404

+ Footer > **More** > "Blog" yields a 404

+ Footer > **Community** - all links point to Docusaurus community pages, which surprised me at first, but now at least I know what platform the new docs are using.

You are probably aware of all these, but didn't see an issue or PR regarding them.

**Comment by Len-PGH** [comment]
Thank you for the report! PR in place, waiting for merge.
